services:
  db:
    image: docker.arvancloud.ir/mariadb:10.9
    volumes:
      - mysql_data:/var/lib/mysql
    container_name: taknews_db
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    networks:
      - app_network
    restart: always
    ports:
      - "3306:3306"

  redis:
    image: docker.arvancloud.ir/redis:7-alpine
    container_name: taknews_redis
    networks:
      - app_network
    restart: always

  web:
    build: .
    container_name: taknews_web
    volumes:
      - ./staticfiles:/app/staticfiles
    environment:
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: db
      DB_PORT: 3306
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0
    ports:
      - "8000:8000"
    networks:
      - app_network
    depends_on:
      - db
      - redis
    restart: always

  celery-worker:
    build: .
    container_name: taknews_celery_worker
    command: sh -c "playwright install chromium && celery -A TakNews worker --loglevel=info --concurrency=4"
    environment:
      PYTHONPATH: /app
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: db
      DB_PORT: 3306
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0
      PLAYWRIGHT_EXECUTABLE_PATH: /usr/bin/chromium
    networks:
      - app_network
    depends_on:
      - db
      - redis
      - web
    restart: always

  celery-beat:
    build: .
    container_name: taknews_celery_beat
    command: sh -c "celery -A TakNews beat --loglevel=info"
    environment:
      PYTHONPATH: /app
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: db
      DB_PORT: 3306
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0
    networks:
      - app_network
    depends_on:
      - db
      - redis
      - web
    restart: always

  flower:
    build: .
    container_name: taknews_flower
    command: sh -c "celery -A TakNews flower --port=5555"
    ports:
      - "5555:5555"
    volumes:
      - .:/app
    environment:
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: db
      DB_PORT: 3306
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0
    networks:
      - app_network
    depends_on:
      - db
      - redis
      - celery-worker
    restart: always

  phpmyadmin:
    image: docker.arvancloud.ir/phpmyadmin
    container_name: taknews_phpmyadmin
    ports:
      - "8050:80"
    environment:
      - PMA_ARBITRARY=0
      - PMA_HOST=db
    networks:
      - app_network
    depends_on:
      - db
    restart: always

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./staticfiles:/app/staticfiles
    depends_on:
      - web
    networks:
      - app_network

volumes:
  mysql_data:
    driver: local

networks:
  app_network:
    driver: bridge
